### ISSUE TITLE
Hi, the menu is missing in magento 1.9.

### ISSUE THREAD

**Issue by viktordodev** [monsieurbiz/Mbiz_AdvancedReports#6]
Hi, I cannot find the menu in the backend.

what is the url path for it?

**Comment by jacquesbh** [comment]
Hi!

Please look at these:
- https://github.com/monsieurbiz/Mbiz_AdvancedReports/blob/master/app/code/community/Mbiz/AdvancedReports/etc/config.xml#L81-L96
- https://github.com/monsieurbiz/Mbiz_AdvancedReports/blob/master/app/code/community/Mbiz/AdvancedReports/etc/adminhtml.xml#L45-L68

Thanks!
